/* PROJETO DA LIVRARIA */

CREATE DATABASE LIVRARIA;

USE LIVRARIA

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100), 
	SEXO CHAR(1), 
	PÁGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	ESTADO CHAR(2),
	ANO INT(4)
);
	
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('SQL para leigos', 'João Nunes', 'M', 450, 'Addison', 98, 'SP', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Receitas Caseiras', 'Celia Tavares', 'F', 210,	'Atlas', 45, 'RJ', 2008);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60, 'MG', 2016);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100, 'ES', 2015);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('Copas Inesqueciveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, ESTADO, ANO) VALUES('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'SP', 2017);

/* QUERIES PRONTAS */

SELECT * FROM LIVROS;

SELECT LIVRO, EDITORA FROM LIVROS;

SELECT LIVRO, ESTADO FROM LIVROS
WHERE SEXO = 'M';

SELECT LIVRO, PÁGINAS FROM LIVROS
WHERE SEXO = 'F';

SELECT VALOR FROM LIVROS
WHERE ESTADO = 'SP';

SELECT AUTOR, ESTADO, SEXO FROM LIVROS
WHERE SEXO = 'M' AND (ESTADO = 'SP' OR ESTADO = 'RJ');